# SIMORGH app-only standalone Gradle properties
org.gradle.jvmargs=-Xmx8192m -XX:MaxMetaspaceSize=2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -Dkotlin.daemon.jvm.options=-Xmx3072m
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=false

kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.daemon.useFallbackStrategy=true
